# Cấu hình cho môi trường Testing
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop # Tạo và xóa schema mỗi lần test
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
  sql:
    init:
      mode: never
      
logging:
  level:
    root: WARN
    iuh.fit.supermarket: INFO
    org.hibernate.SQL: DEBUG
    
server:
  port: 8081
